### PR TITLE
Make sure rounding does not turn null scores to 0.

### LINKED ISSUE #85: Legislators with a 'NaN' score are being shown as '0' instead of '-'
**expected behavior**: when a user clicks a gray district, the legislator's score should be shown as '-'

**current behavior**: when a user clicks a gray district, the legislator's score is '0'

**steps to reproduce**:
1. load the map
2. (example) navigate to Maine Senate District 11
3. notice how the district is gray but the legislator's score is '0'

**fix**:
the score comes directly from the database. if a score is 'NaN', show '-' instead of '0'

### PR DESCRIPTION
**Pull request by mherrero347**
closes #85 - seems as though the rounding that we were doing when rendering the LegislatorDetails component was turning `null` scores into 0's, which is not desirable.

### CODE REVIEW

**Comment by mcchang** [comment]
I think this is okay for now, but we should probably avoid rounding in any frontend applications and just have the API return the rounded (possibly null) score.

**Comment by mcchang** [comment]
Also if you could remove the `.DS_Store` from the commit and add `.DS_Store` to the gitignore file that would be great

**Review by mcchang — APPROVED** [review]

**Comment by mherrero347** [comment]
> I think this is okay for now, but we should probably avoid rounding in any frontend applications and just have the API return the rounded (possibly null) score.

agreed - we originally had decimal points scoped out for legislator pages, but that's been nixed so rounded scores are probably the best option from the API at this point.

**Comment by mcchang** [comment]
> > I think this is okay for now, but we should probably avoid rounding in any frontend applications and just have the API return the rounded (possibly null) score.
> 
> agreed - we originally had decimal points scoped out for legislator pages, but that's been nixed so rounded scores are probably the best option from the API at this point.

Yeah! The nice thing about graphql is the client can select what data they'd like to retrieve from the backend.  For example, we could encapsulate both rounded and raw scores in a `CCScores` object field on `Representative`

```
Representative {
  ccScores {
    score
    rawScore
  }
}
```

**Pull request merged**
